# Chap3.1

Exercise 3.1.1

In [6]:
import numpy as np

x = np.array([[10, 20, 30, 40], 
              [50, 60, 70, 80]])
x

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

Exercise 3.1.2

In [8]:
m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])
print(m.ndim, m.shape)

2 (3, 5)


In [9]:
#n1. 
m[1,2]

7

In [10]:
#n2.
m[-1, -1]

14

In [13]:
#n3.
m[1, 1:3]

array([6, 7])

In [15]:
#n4. 
m[1:, 2]

array([ 7, 12])

In [17]:
#n5. 
m[:2, 3:]

array([[3, 4],
       [8, 9]])

Exercise 3.1.3

In [18]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
#n1. 
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [20]:
#n2. 
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [21]:
#n3. 
x[(x % 3 == 0)&(x % 4 == 1)]

array([9])

# Chap3.2

Exercise 3.2.1

In [29]:
a1 = np.zeros((3,3))
a2 = np.ones((3,2))
a = np.hstack([a1, a2])
a

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [40]:
b = (np.arange(15)+1)*10
b = b.reshape(3,5)
b

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [52]:
c = np.vstack([a,b])
c = np.vstack([c,c])
c

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

Exercise 3.2.2

In [59]:
x = np.random.randint(100, size = 30)
x = x.reshape(5,6)
x

array([[77, 88, 88, 41,  7, 60],
       [86, 31, 48, 34, 55, 29],
       [16, 93, 79,  3, 84, 47],
       [77, 44, 59, 51,  0, 86],
       [ 9,  5, 14, 60,  1, 92]])

In [61]:
#n1.
x.min()

0

In [62]:
#n2.
x.sum(axis = 1)

array([361, 283, 322, 317, 181])

In [63]:
#n3. 
x.max(axis = 1)

array([88, 86, 93, 86, 92])

In [64]:
#n4. 
x.mean(axis = 1)

array([60.16666667, 47.16666667, 53.66666667, 52.83333333, 30.16666667])

In [65]:
x.min(axis = 1)

array([ 7, 29,  3,  0,  1])

# Chap3.3

Exercise 3.3.1

In [69]:
x = np.array([[  1,    2,    3,    4],
              [ 46,   99,  100,   71],
              [ 81,   59,   90,  100]])

In [81]:
np.argsort(x[1, :])
x[:, [0,3,1,2]]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

# Chap3.5

Exercise 3.5.1

In [83]:
x = np.random.choice([0,1], 100, replace = True, p = [.5, .5])
x.mean()

0.49

Exercise 3.5.2

In [84]:
np.random.randn(250)*10000

array([-12324.71398306, -10662.02509181,   1418.61969684, -20399.64234061,
        10145.58937314,   7542.26107245,   7130.6925315 ,  -2283.93346122,
         7504.89654717,  20329.25084521,  -8722.28990331,   5826.65069933,
        -2557.87296725,  24435.16174399,  -7039.34219193, -16962.35781562,
        10295.19031548,   6427.76511512,  -7830.73820924,  -6785.46924369,
         6594.51728147, -15391.30597554,  11247.34326444, -12951.59930137,
        -3103.20606281,  -2579.06523992,   6262.5558417 ,  -6262.16612323,
       -10282.72407569,  -2908.23161707,   7707.40627565,  -4904.93691018,
        -8606.33400887,    201.12772315,   3294.54498027, -18016.98596243,
        -6747.91533912,  20328.50340237,  -9090.08829195,  11959.42047985,
        -8353.73199156,  11667.29392474,  -1742.62809272,  14945.50524798,
        18775.08272946,   8467.13693157,  12488.93775034,  18608.6997729 ,
         6465.06504603,  22658.98053204,  13063.55758657,  -3703.83326319,
         6074.39331172,  