#### Chap3.1 : 넘파이 배열 

많은 숫자 데이터를 하나의 변수에 넣고 관리 할 떄 리스트는 속도가 느리고 메모리를 많이 차지하는 단점이 있다. 배열을 사용하면 적은 메모리로 많은 데이터를 빠르게 처리할 수 있다. 배열은 리스트와 비슷하지만 다음과 같은 점에서 다르다.   

1. 모든 원소가 같은 자료형이어야 한다.
2. 원소의 갯수를 바꿀 수 없다. 
  
파이썬은 자체적으로 배열 자료형을 제공하지 않는다 따라서 배열을 구현한 다른 패키지를 임포트해야 한다. 파이썬에서 배열을 사용하기 위한 표준 패키지는 Numpy이다. 넘파이는 수치해석용 파이썬 패키지로 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용된다. 


##### 벡터화 연산 
배열 객체는 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산을 지원한다. 

#### 2차원 배열 
ndarray는 N-dimensional Array의 약자이다. 이름 그대로 1차원 배열 이외에도 2차원 배열, 3차원 배열 등의 다차원 배열 자료구조를 지원한다. 2차원 배열은 행렬이라고 하는데 행렬에서는 가로줄을 행이라고 하고 세로줄을 열이라고 부른다. 

In [3]:
# Problem 3.1.1
import numpy as np 

ans1 = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
ans1

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [14]:
# Problem 3.1.2 

m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

ans1 = m[1,2]
ans2 = m[-1, -1]
ans3 = m[1, 1:3]
ans4 = m[1:3, 2]
ans5 = m[:2, 3:]
print(ans1, ans2, ans3, ans4, ans5)

7 14 [6 7] [ 7 12] [[3 4]
 [8 9]]


In [15]:
# Problem 3.1.3

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
ans1 = x[x % 3 == 0]
ans2 = x[x % 4 == 1]
ans3 = x[(x % 3 == 0) & (x % 4 == 1)]
print(ans1, ans2, ans3)

[ 3  6  9 12 15 18] [ 1  5  9 13 17] [9]


#### Chap3.2 : 배열의 생성과 변형 

##### 넘파이의 자료형
넘파이의 배열 즉, ndarray클래스는 원소가 모두 같은 자료형이어야 한다. array 명령으로 배열을 만들 때 자료형을 명시적으로 적용하려면 dtype 인수를 사용한다. 만약 dtype 인수가 없으면 주어진 데이터를 저장할 수 있는 자료형을 스스로 유추한다. 

##### 배열생성 

- np.zeros(n) : 크기가 정해져 있고 무든 값이 0인 배열을 생성하려면 zeros명령을 사용한다. 
- np.ones(n) : 0이 아닌 1로 초기화 된 배열을 생성하려면 ones명령을 사용한다. 
- np.ones_like(array, dtype = ' ') or np.zeros_like(array, dtype = ' ') : 만약 크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 배열을 생성할 경우 
- np.empty : 배열의 크기가 커지면 배열을 초기화 하는데도 시간이 걸린다. 이 시간을 단축하려면 배열을 생성만 하고 특정한 값으로 초기화를 하지 않는 empty 명령을 사용할 수 있다. empty 명령으로 생성된 배열에는 기존에 메모리에 저장되어 있던 값이 있으므로 배열의 원소의 값을 미리 알 수 없다. 
- np.arrange() : python의 range()명령, R의 seq()명령과 동일한 작업을 수행한다. 
- np.linspace(0, 100, 5) : 선형 구간 혹은 로그구간을 지정한 수만큼 분할한다.
- np.logspace(0, 100, 5) 

##### 배열 수정 
- A.T : 전치 연산 
- A.reshape((n1, n2)) : 1차원 행렬을 n1, n2형태의 2차원 행렬로 만들 수 있다.
- A.flatten() A.ravel() : 다차원 배열을 1차원 배열로 만든다. 
- np.hstack([m1, m2]) : m1, m2를 행방향으로 연결한다.
- np.vstack([m1, m2]) : m1, m2를 열방향으로 연결한다.
- np.dstack([m1, m2]) : m1, m2를 차원을 추가로 생성한다 

In [10]:
# Problem 3.2.1

m1 = np.zeros((3,3)) 
m2 = np.ones((3,2)) 
m3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])*10
m3 = m3.reshape(3, -1)

a1 = np.hstack([m1, m2])
a2 = np.vstack([a1, m3])
np.tile(a2, (2, 1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

##### 2차원 그리드 생성
변수가 2개인 2차원 함수의 그래프를 그리거나 표를 작성하려면 ㅈ차원 영역에 대한 (x, y)좌표값 쌍 즉, 그리드 포인드(grid point)를 생성하여 각 좌표에 대한 함수값을 계산해야 한다. 예를ㄷ 들어 x, y라는 두변수를 가진 함수에서 x가 0부터 2까지, y가 0부터 4까지의 사각형 영역에서 변화하는 과적을 보고 싶다면 이 사각형 영역 안의 다음과 같은 그리드 포인트 들에 대해 함수를 계산해야 한다. 

#### Chap3.3 : 배열의 연산

In [13]:
# Problem 3.3.1 
X = np.array([range(30)]).reshape(5, -1)

ans1 = np.max(X)
ans2 = np.sum(X)
ans3 = X.sum(axis = 1)
ans4 = X.mean(axis = 1)
ans5 = X.min(axis = 1)
print(ans1, ans2, ans3, ans4, ans5)

29 435 [ 15  51  87 123 159] [ 2.5  8.5 14.5 20.5 26.5] [ 0  6 12 18 24]


In [17]:
# Problem 3.3.2
a = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])

j = np.argsort(a[1, :])
a[:,j]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

#### Chap3.4 : 기술통계  

#### Chap3.5 : 난수 발생과 카운팅

##### 시드 설정하기 
컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아니다. 어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성한다. 이런 시작 숫자를 시드(seed)라고 한다. 일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 된다. 따라서 시드값은 한 번만 정해주면 된다. 시드는 보통 현재 시각등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있다. 특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있다. 이 책에서는 코드의 결과를 재현하기 위해 항상 시드를 설정한다.

- np.random.rand(n) : n 만큼의 0과 1사이의 난수를 발생시킨다.
- np.random.shuffle(x) : array x의 데이터 순서를 바꾼다.

##### 데이터 샘플링
이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것을 표본선택 혹은 샘플링(sampling)이라고 한다. 샘플링에는 choice 함수를 사용한다. choice 함수는 다음과 같은 인수를 가질 수 있다.

numpy.random.choice(a, size=None, replace=True, p=None)

   - a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
   - size : 정수. 샘플 숫자
   - replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능
   - p : 배열. 각 데이터가 선택될 수 있는 확률

##### 난수생성 
- np.random.rand() : rand 함수는 0부터 1사이에서 균일한 확률 분포로 실수 난수를 생성한다. 숫자 인수는 생성할 난수의 크기이다. 여러개의 인수를 넣으면 해당 크기를 가진 행렬을 생성한다.d() : rand 함수는 0부터 1사이에서 균일한 확률 분포로 실수 난수를 생성한다. 숫자 인수는 생성할 난수의 크기이다. 여러개의 인수를 넣으면 해당 크기를 가진 행렬을 생성한다.

- np.random.randn() : randn 함수는 기댓값이 0이고 표준편차가 1인 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성한다. 인수 사용법은 rand 명령과 같다.

- np.random.randint() : randint 함수는 다음과 같은 인수를 가진다.
    - numpy.random.randint(low, high=None, size=None) 만약 high를 입력하지 않으면 0과 low사이의 숫자를, high를 입력하면 low와 high는 사이의 숫자를 출력한다. size는 난수의 숫자이다.

In [3]:
# Problem 3.5.1
ans1 = np.random.choice(np.array([0,1]), 10)
ans2 = np.random.choice(np.array([1, 2, 3, 4, 5, 6]), 100, 
                        p = [1/6, 1/6, 1/6, 1/6, 1/6, 1/6])
ans2 = np.mean(ans2)
print(ans1, ans2)

[1 0 0 1 1 1 0 0 1 1] 3.37


In [5]:
# Problem 3.5.2
income_rate = np.random.randn(250)
income_rate * 10000

array([ 13420.08913833,   2770.07492149,  -6541.39187879,  -6877.44890652,
       -19715.10789626,  -1141.15721506,  -5472.12882678,   2215.97266937,
        12162.51207291, -10113.68317525,   6660.79080631,    565.47183887,
         4746.97862876,  -4551.11634558,  15277.78769476,  15658.11673976,
       -11648.28778904,  -7045.33581826,   9630.3854931 ,   5867.69671781,
        15872.10010055,   5482.38623616,  12872.88729082,   2037.13210791,
         5553.98814045,    235.35687752, -10609.1740826 ,    520.29060834,
        -8200.31796121,  -2400.18978224,   4365.46134418, -22160.59906237,
        -8040.4978294 ,   1449.98477857,   4048.43386305,  -9984.99809259,
       -12610.2434861 ,   8681.88777181,  13110.68018001, -13407.40485664,
        -4235.7567162 ,   6111.82688359,  -7290.1830749 ,   3452.909376  ,
        -5992.79669039,   8186.24590101,  10720.57073839, -11064.41451796,
         8744.56605322,  -2462.47350089,  -1809.11944754,  -7650.50071388,
        -6533.54338351,  

##### 정수데이터 카운팅

- np.unique(x, return_counts = T/F) : x arrray의 unique값을 출력하고 각각의 값에 대한 개수를 출력한다.
- np.bincount(x, minlength = 6) : 확률변수 X에 대하여 측정값이 array x 에 담겨 있지 않는 경우 return_counts를 출력한다.